# =============================================================
#  my_keyboard.conf  —  just feature toggles for the keyb
# wasnt too bad if im being honest
# =============================================================

# Bluetooth
CONFIG_ZMK_BLE=y                        # ON 
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y         # Max BT 
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n  


#USB
CONFIG_ZMK_USB=y                  

# Battery reporting
CONFIG_ZMK_BATTERY_REPORTING=y         # Report battery % to host over BLE

# ── OLED Display (SSD1306-THIS IS A PLACEHOLDER CHANGE IS NEEDED 0.91" over I2C)
CONFIG_ZMK_DISPLAY=y                   
CONFIG_SSD1306=y                       
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y


#SK6812 Mini-E — WS2812-compatible maybe, probably, idk.
CONFIG_ZMK_RGB_UNDERGLOW=y             
CONFIG_WS2812_STRIP=y                  
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y    
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=40  # Start brightness
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0   # Default effect: solid colour

# EC11E
CONFIG_EC11=y                          
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y    #smooth encoder reads yk 
CONFIG_ZMK_ENCODER=y                   # ZMK encoder system


# Power man.
CONFIG_ZMK_SLEEP=y                     # Deep sleep when idle
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000   # Sleep after 15 min idle (ms)
CONFIG_ZMK_IDLE_TIMEOUT=10000         # Dim/lock display after 10 sec idle



#Logging (disable for faster build + less power also not really needed tbh)
CONFIG_ZMK_LOG_LEVEL_DBG=n  
