# =============================================================
#  .github/workflows/build.yml
# please make this worrrrkkkkkkkk
# thank god for this workflow thing on github, took me like 2 hours just to understand
# how it works but still crazy.
# =============================================================

name: Build ZMK Firmware

on:
  push:
  pull_request:
  workflow_dispatch:              

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    # official zmk workflow (hope this works)
